version: '2'

services:
  
  app:
    build: .
    image: chapsuk/crawler
    networks:
      - crawler-net
    command: -h http://golang-book.ru -o /data/
    volumes:
      - ./result/:/data/

  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: crawler
    networks:
      crawler-net:
        aliases:
          - postgres

networks:
  crawler-net:
